version: secqru-standalone-{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
clone_depth: 1
clone_folder: c:\github\deemru\secqru-standalone\
build_script:
- cmd: >-
    echo %time%

    set NOPAUSE=1

    set MAKEZIP=1

    secqru-standalone.bat php54

    copy secqru-standalone.zip secqru-standalone-php54.zip

    rmdir php /s /q

    secqru-standalone.bat php56

    copy secqru-standalone.zip secqru-standalone-php56.zip

    rmdir php /s /q

    secqru-standalone.bat php71

    copy secqru-standalone.zip secqru-standalone-php71.zip
    
    rmdir php /s /q

    secqru-standalone.bat php72

    copy secqru-standalone.zip secqru-standalone-php72.zip

    echo %time%
artifacts:
- path: secqru-standalone-php54.zip
  name: secqru-standalone-php54.zip
- path: secqru-standalone-php56.zip
  name: secqru-standalone-php56.zip
- path: secqru-standalone-php71.zip
  name: secqru-standalone-php71.zip
- path: secqru-standalone-php72.zip
  name: secqru-standalone-php72.zip
deploy:
- provider: GitHub
  auth_token:
    secure: k0qBvpcte6PgNm7deT1NJoObWi/apGm51D1Ll3mlkSZUNcSjO2F0PCuq2cgi5XSu
  artifact: secqru-standalone-php54.zip, secqru-standalone-php56.zip, secqru-standalone-php71.zip, secqru-standalone-php72.zip
  draft: true
